// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"klabel/internal/biz"
	"klabel/internal/conf"
	"klabel/internal/data"
	"klabel/internal/server"
	"klabel/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, qdrant *conf.Qdrant, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	dataData, cleanup, err := data.NewData(confData, qdrant, logger)
	if err != nil {
		return nil, nil, err
	}
	vectorRepo := data.NewVectorRepo(dataData, logger)
	vectorUsecase := biz.NewVectorUsecase(vectorRepo, logger)
	vectorService := service.NewVectorService(vectorUsecase)
	httpServer := server.NewHTTPServer(confServer, vectorService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
