// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/vector/v1/vector.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Close         float32                `protobuf:"fixed32,3,opt,name=close,proto3" json:"close,omitempty"`
	MaxVectors    []float32              `protobuf:"fixed32,4,rep,packed,name=max_vectors,json=maxVectors,proto3" json:"max_vectors,omitempty"`
	MaVectors     []float32              `protobuf:"fixed32,5,rep,packed,name=ma_vectors,json=maVectors,proto3" json:"ma_vectors,omitempty"`
	PriceVectors  []float32              `protobuf:"fixed32,6,rep,packed,name=price_vectors,json=priceVectors,proto3" json:"price_vectors,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorPoint) Reset() {
	*x = VectorPoint{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorPoint) ProtoMessage() {}

func (x *VectorPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorPoint.ProtoReflect.Descriptor instead.
func (*VectorPoint) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{0}
}

func (x *VectorPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorPoint) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *VectorPoint) GetClose() float32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *VectorPoint) GetMaxVectors() []float32 {
	if x != nil {
		return x.MaxVectors
	}
	return nil
}

func (x *VectorPoint) GetMaVectors() []float32 {
	if x != nil {
		return x.MaVectors
	}
	return nil
}

func (x *VectorPoint) GetPriceVectors() []float32 {
	if x != nil {
		return x.PriceVectors
	}
	return nil
}

func (x *VectorPoint) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Close         float32                `protobuf:"fixed32,3,opt,name=close,proto3" json:"close,omitempty"`
	MaxVectors    []float32              `protobuf:"fixed32,4,rep,packed,name=max_vectors,json=maxVectors,proto3" json:"max_vectors,omitempty"`
	MaVectors     []float32              `protobuf:"fixed32,5,rep,packed,name=ma_vectors,json=maVectors,proto3" json:"ma_vectors,omitempty"`
	PriceVectors  []float32              `protobuf:"fixed32,6,rep,packed,name=price_vectors,json=priceVectors,proto3" json:"price_vectors,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{1}
}

func (x *IngestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IngestRequest) GetClose() float32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *IngestRequest) GetMaxVectors() []float32 {
	if x != nil {
		return x.MaxVectors
	}
	return nil
}

func (x *IngestRequest) GetMaVectors() []float32 {
	if x != nil {
		return x.MaVectors
	}
	return nil
}

func (x *IngestRequest) GetPriceVectors() []float32 {
	if x != nil {
		return x.PriceVectors
	}
	return nil
}

func (x *IngestRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Close         *float32               `protobuf:"fixed32,3,opt,name=close,proto3,oneof" json:"close,omitempty"`
	MaxVectors    []float32              `protobuf:"fixed32,4,rep,packed,name=max_vectors,json=maxVectors,proto3" json:"max_vectors,omitempty"`
	MaVectors     []float32              `protobuf:"fixed32,5,rep,packed,name=ma_vectors,json=maVectors,proto3" json:"ma_vectors,omitempty"`
	PriceVectors  []float32              `protobuf:"fixed32,6,rep,packed,name=price_vectors,json=priceVectors,proto3" json:"price_vectors,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *UpdateRequest) GetClose() float32 {
	if x != nil && x.Close != nil {
		return *x.Close
	}
	return 0
}

func (x *UpdateRequest) GetMaxVectors() []float32 {
	if x != nil {
		return x.MaxVectors
	}
	return nil
}

func (x *UpdateRequest) GetMaVectors() []float32 {
	if x != nil {
		return x.MaVectors
	}
	return nil
}

func (x *UpdateRequest) GetPriceVectors() []float32 {
	if x != nil {
		return x.PriceVectors
	}
	return nil
}

func (x *UpdateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{6}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{7}
}

func (x *ListRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*VectorPoint         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{8}
}

func (x *ListResponse) GetItems() []*VectorPoint {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MetricWeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight        float32                `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricWeight) Reset() {
	*x = MetricWeight{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricWeight) ProtoMessage() {}

func (x *MetricWeight) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricWeight.ProtoReflect.Descriptor instead.
func (*MetricWeight) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{9}
}

func (x *MetricWeight) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricWeight) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type QuerySimilarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TopK          uint32                 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MaxVectors    []float32              `protobuf:"fixed32,3,rep,packed,name=max_vectors,json=maxVectors,proto3" json:"max_vectors,omitempty"`
	MaVectors     []float32              `protobuf:"fixed32,4,rep,packed,name=ma_vectors,json=maVectors,proto3" json:"ma_vectors,omitempty"`
	PriceVectors  []float32              `protobuf:"fixed32,5,rep,packed,name=price_vectors,json=priceVectors,proto3" json:"price_vectors,omitempty"`
	Close         float32                `protobuf:"fixed32,6,opt,name=close,proto3" json:"close,omitempty"`
	Metrics       []*MetricWeight        `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySimilarRequest) Reset() {
	*x = QuerySimilarRequest{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySimilarRequest) ProtoMessage() {}

func (x *QuerySimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySimilarRequest.ProtoReflect.Descriptor instead.
func (*QuerySimilarRequest) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{10}
}

func (x *QuerySimilarRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *QuerySimilarRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *QuerySimilarRequest) GetMaxVectors() []float32 {
	if x != nil {
		return x.MaxVectors
	}
	return nil
}

func (x *QuerySimilarRequest) GetMaVectors() []float32 {
	if x != nil {
		return x.MaVectors
	}
	return nil
}

func (x *QuerySimilarRequest) GetPriceVectors() []float32 {
	if x != nil {
		return x.PriceVectors
	}
	return nil
}

func (x *QuerySimilarRequest) GetClose() float32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *QuerySimilarRequest) GetMetrics() []*MetricWeight {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type QuerySimilarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySimilarResponse) Reset() {
	*x = QuerySimilarResponse{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySimilarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySimilarResponse) ProtoMessage() {}

func (x *QuerySimilarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySimilarResponse.ProtoReflect.Descriptor instead.
func (*QuerySimilarResponse) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{11}
}

func (x *QuerySimilarResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	MetricScores  map[string]float32     `protobuf:"bytes,4,rep,name=metric_scores,json=metricScores,proto3" json:"metric_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Point         *VectorPoint           `protobuf:"bytes,5,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_api_vector_v1_vector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_vector_v1_vector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_api_vector_v1_vector_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMetricScores() map[string]float32 {
	if x != nil {
		return x.MetricScores
	}
	return nil
}

func (x *SearchResult) GetPoint() *VectorPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

var File_api_vector_v1_vector_proto protoreflect.FileDescriptor

const file_api_vector_v1_vector_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/vector/v1/vector.proto\x12\tvector.v1\x1a\x1cgoogle/api/annotations.proto\"\xaf\x02\n" +
	"\vVectorPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05close\x18\x03 \x01(\x02R\x05close\x12\x1f\n" +
	"\vmax_vectors\x18\x04 \x03(\x02R\n" +
	"maxVectors\x12\x1d\n" +
	"\n" +
	"ma_vectors\x18\x05 \x03(\x02R\tmaVectors\x12#\n" +
	"\rprice_vectors\x18\x06 \x03(\x02R\fpriceVectors\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.vector.v1.VectorPoint.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x02\n" +
	"\rIngestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05close\x18\x03 \x01(\x02R\x05close\x12\x1f\n" +
	"\vmax_vectors\x18\x04 \x03(\x02R\n" +
	"maxVectors\x12\x1d\n" +
	"\n" +
	"ma_vectors\x18\x05 \x03(\x02R\tmaVectors\x12#\n" +
	"\rprice_vectors\x18\x06 \x03(\x02R\fpriceVectors\x12B\n" +
	"\bmetadata\x18\a \x03(\v2&.vector.v1.IngestRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x0eIngestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc2\x02\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\x05close\x18\x03 \x01(\x02H\x00R\x05close\x88\x01\x01\x12\x1f\n" +
	"\vmax_vectors\x18\x04 \x03(\x02R\n" +
	"maxVectors\x12\x1d\n" +
	"\n" +
	"ma_vectors\x18\x05 \x03(\x02R\tmaVectors\x12#\n" +
	"\rprice_vectors\x18\x06 \x03(\x02R\fpriceVectors\x12B\n" +
	"\bmetadata\x18\a \x03(\v2&.vector.v1.UpdateRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_close\" \n" +
	"\x0eUpdateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"S\n" +
	"\vListRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"R\n" +
	"\fListResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.vector.v1.VectorPointR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\":\n" +
	"\fMetricWeight\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x02R\x06weight\"\xf0\x01\n" +
	"\x13QuerySimilarRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\rR\x04topK\x12\x1f\n" +
	"\vmax_vectors\x18\x03 \x03(\x02R\n" +
	"maxVectors\x12\x1d\n" +
	"\n" +
	"ma_vectors\x18\x04 \x03(\x02R\tmaVectors\x12#\n" +
	"\rprice_vectors\x18\x05 \x03(\x02R\fpriceVectors\x12\x14\n" +
	"\x05close\x18\x06 \x01(\x02R\x05close\x121\n" +
	"\ametrics\x18\a \x03(\v2\x17.vector.v1.MetricWeightR\ametrics\"I\n" +
	"\x14QuerySimilarResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.vector.v1.SearchResultR\aresults\"\x8b\x02\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12N\n" +
	"\rmetric_scores\x18\x04 \x03(\v2).vector.v1.SearchResult.MetricScoresEntryR\fmetricScores\x12,\n" +
	"\x05point\x18\x05 \x01(\v2\x16.vector.v1.VectorPointR\x05point\x1a?\n" +
	"\x11MetricScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x012\xde\x03\n" +
	"\rVectorService\x12V\n" +
	"\x06Ingest\x12\x18.vector.v1.IngestRequest\x1a\x19.vector.v1.IngestResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/vectors\x12[\n" +
	"\x06Update\x12\x18.vector.v1.UpdateRequest\x1a\x19.vector.v1.UpdateResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/vectors/{id}\x12X\n" +
	"\x06Delete\x12\x18.vector.v1.DeleteRequest\x1a\x19.vector.v1.DeleteResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/vectors/{id}\x12M\n" +
	"\x04List\x12\x16.vector.v1.ListRequest\x1a\x17.vector.v1.ListResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/vectors\x12o\n" +
	"\fQuerySimilar\x12\x1e.vector.v1.QuerySimilarRequest\x1a\x1f.vector.v1.QuerySimilarResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/vectors/searchB\x1dZ\x1bhelloworld/api/vector/v1;v1b\x06proto3"

var (
	file_api_vector_v1_vector_proto_rawDescOnce sync.Once
	file_api_vector_v1_vector_proto_rawDescData []byte
)

func file_api_vector_v1_vector_proto_rawDescGZIP() []byte {
	file_api_vector_v1_vector_proto_rawDescOnce.Do(func() {
		file_api_vector_v1_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_vector_v1_vector_proto_rawDesc), len(file_api_vector_v1_vector_proto_rawDesc)))
	})
	return file_api_vector_v1_vector_proto_rawDescData
}

var file_api_vector_v1_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_vector_v1_vector_proto_goTypes = []any{
	(*VectorPoint)(nil),          // 0: vector.v1.VectorPoint
	(*IngestRequest)(nil),        // 1: vector.v1.IngestRequest
	(*IngestResponse)(nil),       // 2: vector.v1.IngestResponse
	(*UpdateRequest)(nil),        // 3: vector.v1.UpdateRequest
	(*UpdateResponse)(nil),       // 4: vector.v1.UpdateResponse
	(*DeleteRequest)(nil),        // 5: vector.v1.DeleteRequest
	(*DeleteResponse)(nil),       // 6: vector.v1.DeleteResponse
	(*ListRequest)(nil),          // 7: vector.v1.ListRequest
	(*ListResponse)(nil),         // 8: vector.v1.ListResponse
	(*MetricWeight)(nil),         // 9: vector.v1.MetricWeight
	(*QuerySimilarRequest)(nil),  // 10: vector.v1.QuerySimilarRequest
	(*QuerySimilarResponse)(nil), // 11: vector.v1.QuerySimilarResponse
	(*SearchResult)(nil),         // 12: vector.v1.SearchResult
	nil,                          // 13: vector.v1.VectorPoint.MetadataEntry
	nil,                          // 14: vector.v1.IngestRequest.MetadataEntry
	nil,                          // 15: vector.v1.UpdateRequest.MetadataEntry
	nil,                          // 16: vector.v1.SearchResult.MetricScoresEntry
}
var file_api_vector_v1_vector_proto_depIdxs = []int32{
	13, // 0: vector.v1.VectorPoint.metadata:type_name -> vector.v1.VectorPoint.MetadataEntry
	14, // 1: vector.v1.IngestRequest.metadata:type_name -> vector.v1.IngestRequest.MetadataEntry
	15, // 2: vector.v1.UpdateRequest.metadata:type_name -> vector.v1.UpdateRequest.MetadataEntry
	0,  // 3: vector.v1.ListResponse.items:type_name -> vector.v1.VectorPoint
	9,  // 4: vector.v1.QuerySimilarRequest.metrics:type_name -> vector.v1.MetricWeight
	12, // 5: vector.v1.QuerySimilarResponse.results:type_name -> vector.v1.SearchResult
	16, // 6: vector.v1.SearchResult.metric_scores:type_name -> vector.v1.SearchResult.MetricScoresEntry
	0,  // 7: vector.v1.SearchResult.point:type_name -> vector.v1.VectorPoint
	1,  // 8: vector.v1.VectorService.Ingest:input_type -> vector.v1.IngestRequest
	3,  // 9: vector.v1.VectorService.Update:input_type -> vector.v1.UpdateRequest
	5,  // 10: vector.v1.VectorService.Delete:input_type -> vector.v1.DeleteRequest
	7,  // 11: vector.v1.VectorService.List:input_type -> vector.v1.ListRequest
	10, // 12: vector.v1.VectorService.QuerySimilar:input_type -> vector.v1.QuerySimilarRequest
	2,  // 13: vector.v1.VectorService.Ingest:output_type -> vector.v1.IngestResponse
	4,  // 14: vector.v1.VectorService.Update:output_type -> vector.v1.UpdateResponse
	6,  // 15: vector.v1.VectorService.Delete:output_type -> vector.v1.DeleteResponse
	8,  // 16: vector.v1.VectorService.List:output_type -> vector.v1.ListResponse
	11, // 17: vector.v1.VectorService.QuerySimilar:output_type -> vector.v1.QuerySimilarResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_vector_v1_vector_proto_init() }
func file_api_vector_v1_vector_proto_init() {
	if File_api_vector_v1_vector_proto != nil {
		return
	}
	file_api_vector_v1_vector_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_vector_v1_vector_proto_rawDesc), len(file_api_vector_v1_vector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_vector_v1_vector_proto_goTypes,
		DependencyIndexes: file_api_vector_v1_vector_proto_depIdxs,
		MessageInfos:      file_api_vector_v1_vector_proto_msgTypes,
	}.Build()
	File_api_vector_v1_vector_proto = out.File
	file_api_vector_v1_vector_proto_goTypes = nil
	file_api_vector_v1_vector_proto_depIdxs = nil
}
